name: Build and Tag LaTeX PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Optional: enables manual trigger from Actions tab

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get short Git hash (changelist)
      id: get_hash
      run: echo "CHANGELIST=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Replace Version Number in LaTeX
      run: |
        sed -i "s/\\\version{.*}/\\\version{${{ env.CHANGELIST }}}/" main.tex

    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex

    - name: Archive Compiled PDF
      uses: actions/upload-artifact@v4
      with:
        name: document-pdf
        path: main.pdf
        retention-days: 14

    - name: Commit compiled PDF
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add main.pdf
        git commit -m "Build PDF for ${{ env.CHANGELIST }}"
        git push
